### ISSUE TITLE
build fail:  Ubuntu Jaunty with rust/snap can't locate eframe 0.19

### ISSUE THREAD

**Issue by akhepcat** [Laar3/PineFlash#1]
Description:    Ubuntu 22.04.1 LTS
Release:        22.04

$ dfu-util -V
dfu-util 0.11-dev

$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)

$ rustup show 
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/snap/rustup/common/rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

~~PineFlash$ cargo build --release 
    Updating crates.io index
error: failed to select a version for the requirement `eframe = "^0.19.0"`
candidate versions found which didn't match: 0.17.0, 0.16.0, 0.15.0, ...
location searched: crates.io index
required by package `pineflash v0.2.0 (/usr/local/src/PineFlash)`

**Comment by Laar3** [comment]
That is quite weird, i'm not certain why its not able to find eframe. If you move eframe to go underneath the other dependancies is it able to find the others and just not eframe or is it not able to find any crates at all?

**Comment by akhepcat** [comment]
If i comment out eframe and egui-notify, everything else works fine.

$ cargo tree -e features
pineflash v0.2.0 (/usr/local/src/PineFlash)
├── ehttp feature "default"
│   └── ehttp v0.2.0
│       ├── ureq feature "default"
│       │   ├── ureq v2.5.0
│       │   │   ├── base64 feature "default"
│       │   │   │   ├── base64 v0.13.0
│       │   │   │   └── base64 feature "std"
│       │   │   │       └── base64 v0.13.0
│       │   │   ├── chunked_transfer feature "default"
│       │   │   │   └── chunked_transfer v1.4.0
│       │   │   ├── flate2 feature "default"
│       │   │   │   ├── flate2 v1.0.24
│       │   │   │   │   ├── miniz_oxide v0.5.4
│       │   │   │   │   │   └── adler v1.0.2
│       │   │   │   │   └── crc32fast feature "default"
│       │   │   │   │       ├── crc32fast v1.3.2
│       │   │   │   │       │   └── cfg-if feature "default"
│       │   │   │   │       │       └── cfg-if v1.0.0
│       │   │   │   │       └── crc32fast feature "std"
│       │   │   │   │           └── crc32fast v1.3.2 (*)
│       │   │   │   └── flate2 feature "rust_backend"
│       │   │   │       ├── flate2 v1.0.24 (*)
│       │   │   │       └── flate2 feature "miniz_oxide"
│       │   │   │           └── flate2 v1.0.24 (*)
│       │   │   ├── log feature "default"
│       │   │   │   └── log v0.4.17
│       │   │   │       └── cfg-if feature "default" (*)
│       │   │   ├── once_cell feature "default"
│       │   │   │   ├── once_cell v1.15.0
│       │   │   │   └── once_cell feature "std"
│       │   │   │       ├── once_cell v1.15.0
│       │   │   │       └── once_cell feature "alloc"
│       │   │   │           ├── once_cell v1.15.0
│       │   │   │           └── once_cell feature "race"
│       │   │   │               └── once_cell v1.15.0
│       │   │   ├── rustls feature "default"
│       │   │   │   ├── rustls v0.20.6
│       │   │   │   │   ├── log feature "default" (*)
│       │   │   │   │   ├── ring feature "default"
│       │   │   │   │   │   ├── ring v0.16.20
│       │   │   │   │   │   │   ├── libc v0.2.133
│       │   │   │   │   │   │   ├── spin v0.5.2
│       │   │   │   │   │   │   ├── once_cell feature "std" (*)
│       │   │   │   │   │   │   └── untrusted feature "default"
│       │   │   │   │   │   │       └── untrusted v0.7.1
│       │   │   │   │   │   │   [build-dependencies]
│       │   │   │   │   │   │   └── cc v1.0.73
│       │   │   │   │   │   ├── ring feature "alloc"
│       │   │   │   │   │   │   └── ring v0.16.20 (*)
│       │   │   │   │   │   └── ring feature "dev_urandom_fallback"
│       │   │   │   │   │       ├── ring v0.16.20 (*)
│       │   │   │   │   │       └── ring feature "once_cell"
│       │   │   │   │   │           └── ring v0.16.20 (*)
│       │   │   │   │   ├── sct feature "default"
│       │   │   │   │   │   └── sct v0.7.0
│       │   │   │   │   │       ├── ring feature "default" (*)
│       │   │   │   │   │       └── untrusted feature "default" (*)
│       │   │   │   │   ├── webpki feature "alloc"
│       │   │   │   │   │   ├── webpki v0.22.0
│       │   │   │   │   │   │   ├── ring v0.16.20 (*)
│       │   │   │   │   │   │   └── untrusted feature "default" (*)
│       │   │   │   │   │   └── ring feature "alloc" (*)
│       │   │   │   │   ├── webpki feature "default"
│       │   │   │   │   │   └── webpki v0.22.0 (*)
│       │   │   │   │   └── webpki feature "std"
│       │   │   │   │       ├── webpki v0.22.0 (*)
│       │   │   │   │       └── webpki feature "alloc" (*)
│       │   │   │   ├── rustls feature "logging"
│       │   │   │   │   ├── rustls v0.20.6 (*)
│       │   │   │   │   └── rustls feature "log"
│       │   │   │   │       └── rustls v0.20.6 (*)
│       │   │   │   └── rustls feature "tls12"
│       │   │   │       └── rustls v0.20.6 (*)
│       │   │   ├── webpki feature "default" (*)
│       │   │   ├── url feature "default"
│       │   │   │   └── url v2.3.1
│       │   │   │       ├── form_urlencoded feature "default"
│       │   │   │       │   └── form_urlencoded v1.1.0
│       │   │   │       │       └── percent-encoding feature "default"
│       │   │   │       │           ├── percent-encoding v2.2.0
│       │   │   │       │           └── percent-encoding feature "alloc"
│       │   │   │       │               └── percent-encoding v2.2.0
│       │   │   │       ├── percent-encoding feature "default" (*)
│       │   │   │       └── idna feature "default"
│       │   │   │           └── idna v0.3.0
│       │   │   │               ├── unicode-bidi feature "default"
│       │   │   │               │   ├── unicode-bidi v0.3.8
│       │   │   │               │   ├── unicode-bidi feature "hardcoded-data"
│       │   │   │               │   │   └── unicode-bidi v0.3.8
│       │   │   │               │   └── unicode-bidi feature "std"
│       │   │   │               │       └── unicode-bidi v0.3.8
│       │   │   │               └── unicode-normalization feature "default"
│       │   │   │                   ├── unicode-normalization v0.1.22
│       │   │   │                   │   ├── tinyvec feature "alloc"
│       │   │   │                   │   │   ├── tinyvec v1.6.0
│       │   │   │                   │   │   │   └── tinyvec_macros feature "default"
│       │   │   │                   │   │   │       └── tinyvec_macros v0.1.0
│       │   │   │                   │   │   └── tinyvec feature "tinyvec_macros"
│       │   │   │                   │   │       └── tinyvec v1.6.0 (*)
│       │   │   │                   │   └── tinyvec feature "default"
│       │   │   │                   │       └── tinyvec v1.6.0 (*)
│       │   │   │                   └── unicode-normalization feature "std"
│       │   │   │                       └── unicode-normalization v0.1.22 (*)
│       │   │   └── webpki-roots feature "default"
│       │   │       └── webpki-roots v0.22.5
│       │   │           └── webpki feature "default" (*)
│       │   ├── ureq feature "gzip"
│       │   │   ├── ureq v2.5.0 (*)
│       │   │   └── ureq feature "flate2"
│       │   │       └── ureq v2.5.0 (*)
│       │   └── ureq feature "tls"
│       │       ├── ureq v2.5.0 (*)
│       │       ├── ureq feature "rustls"
│       │       │   └── ureq v2.5.0 (*)
│       │       ├── ureq feature "webpki"
│       │       │   └── ureq v2.5.0 (*)
│       │       └── ureq feature "webpki-roots"
│       │           └── ureq v2.5.0 (*)
│       ├── web-sys feature "Headers"
│       │   └── web-sys v0.3.60
│       │       ├── js-sys feature "default"
│       │       │   └── js-sys v0.3.60
│       │       │       └── wasm-bindgen feature "default"
│       │       │           ├── wasm-bindgen v0.2.83
│       │       │           │   ├── cfg-if feature "default" (*)
│       │       │           │   └── wasm-bindgen-macro feature "default"
│       │       │           │       └── wasm-bindgen-macro v0.2.83 (proc-macro)
│       │       │           │           ├── quote feature "default"
│       │       │           │           │   ├── quote v1.0.21
│       │       │           │           │   │   └── proc-macro2 v1.0.45
│       │       │           │           │   │       └── unicode-ident feature "default"
│       │       │           │           │   │           └── unicode-ident v1.0.4
│       │       │           │           │   └── quote feature "proc-macro"
│       │       │           │           │       ├── quote v1.0.21 (*)
│       │       │           │           │       └── proc-macro2 feature "proc-macro"
│       │       │           │           │           └── proc-macro2 v1.0.45 (*)
│       │       │           │           └── wasm-bindgen-macro-support feature "default"
│       │       │           │               └── wasm-bindgen-macro-support v0.2.83
│       │       │           │                   ├── quote feature "default" (*)
│       │       │           │                   ├── proc-macro2 feature "default"
│       │       │           │                   │   ├── proc-macro2 v1.0.45 (*)
│       │       │           │                   │   └── proc-macro2 feature "proc-macro" (*)
│       │       │           │                   ├── syn feature "default"
│       │       │           │                   │   ├── syn v1.0.101
│       │       │           │                   │   │   ├── proc-macro2 v1.0.45 (*)
│       │       │           │                   │   │   ├── quote v1.0.21 (*)
│       │       │           │                   │   │   └── unicode-ident feature "default" (*)
│       │       │           │                   │   ├── syn feature "clone-impls"
│       │       │           │                   │   │   └── syn v1.0.101 (*)
│       │       │           │                   │   ├── syn feature "derive"
│       │       │           │                   │   │   └── syn v1.0.101 (*)
│       │       │           │                   │   ├── syn feature "parsing"
│       │       │           │                   │   │   └── syn v1.0.101 (*)
│       │       │           │                   │   ├── syn feature "printing"
│       │       │           │                   │   │   ├── syn v1.0.101 (*)
│       │       │           │                   │   │   └── syn feature "quote"
│       │       │           │                   │   │       └── syn v1.0.101 (*)
│       │       │           │                   │   └── syn feature "proc-macro"
│       │       │           │                   │       ├── syn v1.0.101 (*)
│       │       │           │                   │       ├── quote feature "proc-macro" (*)
│       │       │           │                   │       ├── proc-macro2 feature "proc-macro" (*)
│       │       │           │                   │       └── syn feature "quote" (*)
│       │       │           │                   ├── syn feature "full"
│       │       │           │                   │   └── syn v1.0.101 (*)
│       │       │           │                   ├── syn feature "visit"
│       │       │           │                   │   └── syn v1.0.101 (*)
│       │       │           │                   ├── wasm-bindgen-backend feature "default"
│       │       │           │                   │   └── wasm-bindgen-backend v0.2.83
│       │       │           │                   │       ├── log feature "default" (*)
│       │       │           │                   │       ├── once_cell feature "default" (*)
│       │       │           │                   │       ├── quote feature "default" (*)
│       │       │           │                   │       ├── proc-macro2 feature "default" (*)
│       │       │           │                   │       ├── syn feature "default" (*)
│       │       │           │                   │       ├── syn feature "full" (*)
│       │       │           │                   │       ├── bumpalo feature "default"
│       │       │           │                   │       │   └── bumpalo v3.11.0
│       │       │           │                   │       └── wasm-bindgen-shared feature "default"
│       │       │           │                   │           └── wasm-bindgen-shared v0.2.83
│       │       │           │                   └── wasm-bindgen-shared feature "default" (*)
│       │       │           ├── wasm-bindgen feature "spans"
│       │       │           │   ├── wasm-bindgen v0.2.83 (*)
│       │       │           │   └── wasm-bindgen-macro feature "spans"
│       │       │           │       ├── wasm-bindgen-macro v0.2.83 (proc-macro) (*)
│       │       │           │       └── wasm-bindgen-macro-support feature "spans"
│       │       │           │           ├── wasm-bindgen-macro-support v0.2.83 (*)
│       │       │           │           └── wasm-bindgen-backend feature "spans"
│       │       │           │               └── wasm-bindgen-backend v0.2.83 (*)
│       │       │           └── wasm-bindgen feature "std"
│       │       │               └── wasm-bindgen v0.2.83 (*)
│       │       └── wasm-bindgen feature "default" (*)
│       ├── web-sys feature "Request"
│       │   └── web-sys v0.3.60 (*)
│       ├── web-sys feature "RequestInit"
│       │   └── web-sys v0.3.60 (*)
│       ├── web-sys feature "RequestMode"
│       │   └── web-sys v0.3.60 (*)
│       ├── web-sys feature "Response"
│       │   └── web-sys v0.3.60 (*)
│       ├── web-sys feature "Window"
│       │   ├── web-sys v0.3.60 (*)
│       │   └── web-sys feature "EventTarget"
│       │       └── web-sys v0.3.60 (*)
│       └── web-sys feature "default"
│           └── web-sys v0.3.60 (*)
├── poll-promise feature "default"
│   └── poll-promise v0.1.0
│       └── static_assertions feature "default"
│           └── static_assertions v1.1.0
├── regex feature "default"
│   ├── regex v1.6.0
│   │   ├── regex-syntax v0.6.27
│   │   ├── aho-corasick feature "default"
│   │   │   ├── aho-corasick v0.7.19
│   │   │   │   └── memchr v2.5.0
│   │   │   └── aho-corasick feature "std"
│   │   │       ├── aho-corasick v0.7.19 (*)
│   │   │       └── memchr feature "std"
│   │   │           └── memchr v2.5.0
│   │   └── memchr feature "default"
│   │       ├── memchr v2.5.0
│   │       └── memchr feature "std" (*)
│   ├── regex feature "perf"
│   │   ├── regex v1.6.0 (*)
│   │   ├── regex feature "perf-cache"
│   │   │   └── regex v1.6.0 (*)
│   │   ├── regex feature "perf-dfa"
│   │   │   └── regex v1.6.0 (*)
│   │   ├── regex feature "perf-inline"
│   │   │   └── regex v1.6.0 (*)
│   │   └── regex feature "perf-literal"
│   │       ├── regex v1.6.0 (*)
│   │       ├── regex feature "aho-corasick"
│   │       │   └── regex v1.6.0 (*)
│   │       └── regex feature "memchr"
│   │           └── regex v1.6.0 (*)
│   ├── regex feature "std"
│   │   └── regex v1.6.0 (*)
│   ├── regex feature "unicode"
│   │   ├── regex v1.6.0 (*)
│   │   ├── regex feature "unicode-age"
│   │   │   ├── regex v1.6.0 (*)
│   │   │   └── regex-syntax feature "unicode-age"
│   │   │       └── regex-syntax v0.6.27
│   │   ├── regex feature "unicode-bool"
│   │   │   ├── regex v1.6.0 (*)
│   │   │   └── regex-syntax feature "unicode-bool"
│   │   │       └── regex-syntax v0.6.27
│   │   ├── regex feature "unicode-case"
│   │   │   ├── regex v1.6.0 (*)
│   │   │   └── regex-syntax feature "unicode-case"
│   │   │       └── regex-syntax v0.6.27
│   │   ├── regex feature "unicode-gencat"
│   │   │   ├── regex v1.6.0 (*)
│   │   │   └── regex-syntax feature "unicode-gencat"
│   │   │       └── regex-syntax v0.6.27
│   │   ├── regex feature "unicode-perl"
│   │   │   ├── regex v1.6.0 (*)
│   │   │   └── regex-syntax feature "unicode-perl"
│   │   │       └── regex-syntax v0.6.27
│   │   ├── regex feature "unicode-script"
│   │   │   ├── regex v1.6.0 (*)
│   │   │   └── regex-syntax feature "unicode-script"
│   │   │       └── regex-syntax v0.6.27
│   │   ├── regex feature "unicode-segment"
│   │   │   ├── regex v1.6.0 (*)
│   │   │   └── regex-syntax feature "unicode-segment"
│   │   │       └── regex-syntax v0.6.27
│   │   └── regex-syntax feature "unicode"
│   │       ├── regex-syntax v0.6.27
│   │       ├── regex-syntax feature "unicode-age" (*)
│   │       ├── regex-syntax feature "unicode-bool" (*)
│   │       ├── regex-syntax feature "unicode-case" (*)
│   │       ├── regex-syntax feature "unicode-gencat" (*)
│   │       ├── regex-syntax feature "unicode-perl" (*)
│   │       ├── regex-syntax feature "unicode-script" (*)
│   │       └── regex-syntax feature "unicode-segment" (*)
│   └── regex-syntax feature "default"
│       ├── regex-syntax v0.6.27
│       └── regex-syntax feature "unicode" (*)
├── rfd feature "default"
│   ├── rfd v0.10.0
│   │   ├── log feature "default" (*)
│   │   ├── glib-sys feature "default"
│   │   │   └── glib-sys v0.15.10
│   │   │       └── libc feature "default"
│   │   │           ├── libc v0.2.133
│   │   │           └── libc feature "std"
│   │   │               └── libc v0.2.133
│   │   │       [build-dependencies]
│   │   │       └── system-deps feature "default"
│   │   │           └── system-deps v6.0.2
│   │   │               ├── toml v0.5.9
│   │   │               │   └── serde feature "default"
│   │   │               │       ├── serde v1.0.145
│   │   │               │       └── serde feature "std"
│   │   │               │           └── serde v1.0.145
│   │   │               ├── cfg-expr feature "default"
│   │   │               │   └── cfg-expr v0.10.3
│   │   │               │       └── smallvec feature "default"
│   │   │               │           └── smallvec v1.9.0
│   │   │               ├── heck feature "default"
│   │   │               │   └── heck v0.4.0
│   │   │               ├── pkg-config feature "default"
│   │   │               │   └── pkg-config v0.3.25
│   │   │               └── version-compare feature "default"
│   │   │                   └── version-compare v0.1.0
│   │   ├── gobject-sys feature "default"
│   │   │   └── gobject-sys v0.15.10
│   │   │       ├── libc feature "default" (*)
│   │   │       └── glib-sys feature "default" (*)
│   │   │       [build-dependencies]
│   │   │       └── system-deps feature "default" (*)
│   │   ├── gtk-sys feature "default"
│   │   │   └── gtk-sys v0.15.3
│   │   │       ├── libc feature "default" (*)
│   │   │       ├── glib-sys feature "default" (*)
│   │   │       ├── gobject-sys feature "default" (*)
│   │   │       ├── atk-sys feature "default"
│   │   │       │   └── atk-sys v0.15.1
│   │   │       │       ├── libc feature "default" (*)
│   │   │       │       ├── glib-sys feature "default" (*)
│   │   │       │       └── gobject-sys feature "default" (*)
│   │   │       │       [build-dependencies]
│   │   │       │       └── system-deps feature "default" (*)
│   │   │       ├── cairo-sys-rs feature "default"
│   │   │       │   └── cairo-sys-rs v0.15.1
│   │   │       │       └── libc feature "default" (*)
│   │   │       │       [build-dependencies]
│   │   │       │       └── system-deps feature "default" (*)
│   │   │       ├── gdk-pixbuf-sys feature "default"
│   │   │       │   └── gdk-pixbuf-sys v0.15.10
│   │   │       │       ├── libc feature "default" (*)
│   │   │       │       ├── glib-sys feature "default" (*)
│   │   │       │       ├── gobject-sys feature "default" (*)
│   │   │       │       └── gio-sys feature "default"
│   │   │       │           └── gio-sys v0.15.10
│   │   │       │               ├── libc feature "default" (*)
│   │   │       │               ├── glib-sys feature "default" (*)
│   │   │       │               └── gobject-sys feature "default" (*)
│   │   │       │               [build-dependencies]
│   │   │       │               └── system-deps feature "default" (*)
│   │   │       │       [build-dependencies]
│   │   │       │       └── system-deps feature "default" (*)
│   │   │       ├── gio-sys feature "default" (*)
│   │   │       ├── gdk-sys feature "default"
│   │   │       │   └── gdk-sys v0.15.1
│   │   │       │       ├── libc feature "default" (*)
│   │   │       │       ├── glib-sys feature "default" (*)
│   │   │       │       ├── gobject-sys feature "default" (*)
│   │   │       │       ├── cairo-sys-rs feature "default" (*)
│   │   │       │       ├── gdk-pixbuf-sys feature "default" (*)
│   │   │       │       ├── gio-sys feature "default" (*)
│   │   │       │       └── pango-sys feature "default"
│   │   │       │           └── pango-sys v0.15.10
│   │   │       │               ├── libc feature "default" (*)
│   │   │       │               ├── glib-sys feature "default" (*)
│   │   │       │               └── gobject-sys feature "default" (*)
│   │   │       │               [build-dependencies]
│   │   │       │               └── system-deps feature "default" (*)
│   │   │       │       [build-dependencies]
│   │   │       │       ├── system-deps feature "default" (*)
│   │   │       │       └── pkg-config feature "default" (*)
│   │   │       └── pango-sys feature "default" (*)
│   │   │       [build-dependencies]
│   │   │       └── system-deps feature "default" (*)
│   │   ├── gtk-sys feature "v3_20"
│   │   │   └── gtk-sys v0.15.3 (*)
│   │   ├── lazy_static feature "default"
│   │   │   └── lazy_static v1.4.0
│   │   └── raw-window-handle feature "default"
│   │       └── raw-window-handle v0.5.0
│   │           └── cty feature "default"
│   │               └── cty v0.2.2
│   └── rfd feature "gtk3"
│       ├── rfd v0.10.0 (*)
│       ├── rfd feature "glib-sys"
│       │   └── rfd v0.10.0 (*)
│       ├── rfd feature "gobject-sys"
│       │   └── rfd v0.10.0 (*)
│       ├── rfd feature "gtk-sys"
│       │   └── rfd v0.10.0 (*)
│       └── rfd feature "lazy_static"
│           └── rfd v0.10.0 (*)
├── tinyjson feature "default"
│   └── tinyjson v2.5.0
├── whoami feature "default"
│   └── whoami v1.2.3
└── zip-extract feature "default"
    ├── zip-extract v0.1.1
    │   ├── log feature "default" (*)
    │   ├── thiserror feature "default"
    │   │   └── thiserror v1.0.37
    │   │       └── thiserror-impl feature "default"
    │   │           └── thiserror-impl v1.0.37 (proc-macro)
    │   │               ├── quote feature "default" (*)
    │   │               ├── proc-macro2 feature "default" (*)
    │   │               └── syn feature "default" (*)
    │   └── zip feature "default"
    │       ├── zip v0.5.13
    │       │   ├── flate2 v1.0.24 (*)
    │       │   ├── crc32fast feature "default" (*)
    │       │   ├── thiserror feature "default" (*)
    │       │   ├── byteorder feature "default"
    │       │   │   ├── byteorder v1.4.3
    │       │   │   └── byteorder feature "std"
    │       │   │       └── byteorder v1.4.3
    │       │   ├── bzip2 feature "default"
    │       │   │   └── bzip2 v0.4.3
    │       │   │       ├── libc feature "default" (*)
    │       │   │       └── bzip2-sys feature "default"
    │       │   │           └── bzip2-sys v0.1.11+1.0.8
    │       │   │               └── libc feature "default" (*)
    │       │   │               [build-dependencies]
    │       │   │               ├── cc feature "default"
    │       │   │               │   └── cc v1.0.73
    │       │   │               └── pkg-config feature "default" (*)
    │       │   └── time feature "default"
    │       │       └── time v0.1.44
    │       │           └── libc feature "default" (*)
    │       ├── zip feature "bzip2"
    │       │   └── zip v0.5.13 (*)
    │       ├── zip feature "deflate"
    │       │   ├── zip v0.5.13 (*)
    │       │   ├── flate2 feature "rust_backend" (*)
    │       │   └── zip feature "flate2"
    │       │       └── zip v0.5.13 (*)
    │       └── zip feature "time"
    │           └── zip v0.5.13 (*)
    ├── zip-extract feature "bzip2"
    │   ├── zip-extract v0.1.1 (*)
    │   └── zip feature "bzip2" (*)
    └── zip-extract feature "deflate"
        ├── zip-extract v0.1.1 (*)
        └── zip feature "deflate" (*)

**Comment by akhepcat** [comment]
$ cargo tree -e features
    Updating crates.io index
error: failed to select a version for the requirement `egui = "^0.19"`
candidate versions found which didn't match: 0.17.0, 0.16.1, 0.16.0, ...
location searched: crates.io index
required by package `egui-notify v0.4.0`
    ... which satisfies dependency `egui-notify = "^0.4"` of package `pineflash v0.2.0 (/usr/local/src/PineFlash)`

**Comment by akhepcat** [comment]
BUT:

$ cargo search eframe
eframe = "0.19.0"           # egui framework - write GUI apps that compiles to web and/or natively

$ cargo search egui-notify
egui-notify = "0.4.0"    # Simple notifications library for EGUI

not sure what's going on here... very odd

**Comment by Laar3** [comment]
Hi, sorry but i really have no clue how to approach this issue, could be an issue with how snap sandboxes things? im really not sure

**Comment by Laar3** [comment]
Does it still fail to build or have the rust updates since then fixed the issue? I think im going to close it as i cant reproduce and it doesnt seem to be a problem due to this project but if you disagree feel free to reopen it.

**Comment by akhepcat** [comment]
AH, I've since upgraded to Ubuntu Kinetic, and don't seem to have the same issue anymore.

current git pull builds and runs successfully, once  libgtk-3-dev  is installed.

**Comment by Laar3** [comment]
great, glad to hear its working now
